USE eu;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Records of quartz_job
-- ----------------------------
BEGIN;
INSERT INTO `quartz_job` (`id`, `job_name`, `job_group`, `cron`, `status`, `misfire_policy`, `concurrent`, `invoke_class_name`, `spring_bean_name`, `method_name`, `method_params`, `pause_after_failure`, `alarm_email`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`) VALUES ('1672495122451099649', '测试内容', 'DEFAULT', '0/5 * * * * ?', 1, 0, 0, NULL, 'testJob', 'run', 'abc', b'0', NULL, '1', '2023-06-24 06:41:25', '1', '2023-10-12 03:34:22', NULL, 0);
COMMIT;

-- ----------------------------
-- Records of sys_menu
-- ----------------------------
BEGIN;
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (1, '首页', 'workbench', 10, NULL, '/', NULL, NULL, 0, b'0', b'1', b'1', b'0', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, '2023-06-05 08:18:37', '1', '2023-10-20 09:19:52', NULL, 0, b'0');
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (10, '工作台', 'workbench', 10, NULL, '/workbench', 'Workbench', 'workbench/index', 0, b'1', b'1', b'1', b'0', NULL, b'0', NULL, 2, 1, b'1', b'1', NULL, '2023-06-05 08:18:37', '1', '2023-10-20 09:19:52', NULL, 0, b'0');
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (20, '系统设置', 'shezhi', 20, NULL, '/system', NULL, NULL, 0, b'0', b'1', NULL, b'0', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, '2023-06-05 08:18:37', '1', '2023-10-20 09:19:52', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (30, '系统工具', 'gongju', 40, NULL, '/tools', NULL, NULL, 0, b'0', b'1', NULL, b'0', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, '2023-06-05 08:18:38', '1', '2023-10-20 09:19:52', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (50, '关于', 'yingyongkaifazhe', 999, NULL, 'https://gitee.com/zhaoeryu/eu-backend-web', '', '', 0, b'0', b'1', b'0', b'0', NULL, b'0', NULL, 2, NULL, b'0', b'0', NULL, '2023-06-05 08:18:38', '1', '2023-10-20 09:19:52', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (1000, '个人中心', NULL, 10, NULL, '/personal-center', 'PersonalCenter', 'system/personal-center', 0, b'0', b'1', b'1', b'0', NULL, b'0', NULL, 2, 20, b'1', b'1', NULL, '2023-06-05 08:18:37', '1', '2023-10-20 09:19:52', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (1010, '用户管理', NULL, 20, 'system:user:list', '/users', 'Users', 'system/users', 0, b'0', b'1', b'1', b'0', NULL, b'1', NULL, 2, 20, b'1', b'1', NULL, '2023-06-05 08:18:37', '1', '2023-10-20 09:19:52', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (1015, '部门管理', NULL, 30, 'system:dept:list', '/depts', 'Depts', 'system/depts', 0, b'0', b'1', b'1', b'0', NULL, NULL, NULL, 2, 20, b'1', b'1', NULL, '2023-06-05 08:18:37', '1', '2023-10-20 09:19:52', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (1020, '岗位管理', NULL, 40, 'system:post:list', '/posts', 'Posts', 'system/posts', 0, b'0', b'1', b'1', b'0', NULL, NULL, NULL, 2, 20, b'1', b'1', NULL, '2023-06-05 08:18:37', '1', '2023-10-20 09:19:52', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (1030, '角色管理', NULL, 50, 'system:role:list', '/roles', 'Roles', 'system/roles', 0, b'0', b'1', b'1', b'0', NULL, NULL, NULL, 2, 20, b'1', b'1', NULL, '2023-06-05 08:18:37', '1', '2023-10-20 09:19:52', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (1031, '角色成员', NULL, 130, 'system:role:assign:list', '/roles/auth-user/:roleId', 'AuthUser', 'system/roles/auth-user', 0, b'0', b'0', b'0', b'0', NULL, b'0', NULL, 2, 20, b'1', b'1', NULL, '2023-06-05 08:18:37', '1', '2023-10-20 09:19:52', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (1040, '菜单管理', NULL, 60, 'system:menu:list', '/menus', 'Menus', 'system/menus', 0, b'0', b'1', b'1', b'0', NULL, NULL, NULL, 2, 20, b'1', b'1', NULL, '2023-06-05 08:18:37', '1', '2023-10-20 09:19:52', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (1050, '字典管理', NULL, 70, 'system:dict:list', '/dicts', 'Dicts', 'system/dicts', 0, b'0', b'1', b'1', b'0', NULL, NULL, NULL, 2, 20, b'1', b'1', NULL, '2023-06-05 08:18:37', '1', '2023-10-20 09:19:52', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (1060, '任务管理', NULL, 80, 'system:job:list', '/jobs', 'Jobs', 'system/jobs', 0, b'0', b'1', b'1', b'0', NULL, b'1', NULL, 2, 20, b'1', b'1', NULL, '2023-06-05 08:18:37', '1', '2023-10-20 09:19:52', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (1070, '操作日志', NULL, 90, 'system:oper-log:list', '/oper-logs', 'OperLogs', 'system/oper-logs', 0, b'0', b'1', b'1', b'0', NULL, b'0', NULL, 2, 2145, b'1', b'1', NULL, '2023-06-05 08:18:37', '1', '2023-10-20 09:19:52', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (1100, '快捷菜单', NULL, 120, 'system:usual-menus:list', '/usual-menus', 'UsualMenus', 'system/usual-menus', 0, b'0', b'1', b'1', b'0', NULL, b'0', 'New', 2, 20, b'1', b'0', NULL, '2023-06-05 08:18:37', '1', '2023-10-20 09:19:52', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2100, '代码生成', NULL, 10, 'tools:gen', '/gen', 'Gen', 'tools/generate', 0, b'0', b'1', b'1', b'0', NULL, b'0', NULL, 2, 30, b'1', b'1', NULL, '2023-06-05 08:18:38', '1', '2023-10-20 09:19:52', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2110, '系统接口', NULL, 20, '', '/swagger', NULL, 'tools/swagger', 0, b'0', b'1', b'1', b'1', 'http://localhost:8000/api/doc.html', b'1', NULL, 2, 30, b'0', b'0', NULL, '2023-06-05 08:18:38', '1', '2023-10-20 09:20:00', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2115, '新增', NULL, 0, 'system:role:add', NULL, NULL, NULL, 0, b'0', b'0', b'0', b'0', NULL, b'0', NULL, 3, 1030, NULL, NULL, NULL, '2023-06-08 08:56:00', NULL, '2023-06-08 08:56:00', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2116, '修改', NULL, 0, 'system:role:edit', NULL, NULL, NULL, 0, b'0', b'0', b'0', b'0', NULL, b'0', NULL, 3, 1030, NULL, NULL, NULL, '2023-06-08 08:56:00', NULL, '2023-06-08 08:56:00', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2117, '删除', NULL, 0, 'system:role:del', NULL, NULL, NULL, 0, b'0', b'0', b'0', b'0', NULL, b'0', NULL, 3, 1030, NULL, NULL, NULL, '2023-06-08 08:56:00', NULL, '2023-06-08 08:56:00', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2118, '查询单个值', NULL, 0, 'system:role:query', NULL, NULL, NULL, 0, b'0', b'0', b'0', b'0', NULL, b'0', NULL, 3, 1030, NULL, NULL, NULL, '2023-06-08 08:56:00', NULL, '2023-06-08 08:56:00', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2119, '新增', NULL, 0, 'system:post:add', NULL, NULL, NULL, 0, b'0', b'0', b'0', b'0', NULL, b'0', NULL, 3, 1020, NULL, NULL, NULL, '2023-06-08 09:02:31', NULL, '2023-06-08 09:02:31', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2120, '修改', NULL, 0, 'system:post:edit', NULL, NULL, NULL, 0, b'0', b'0', b'0', b'0', NULL, b'0', NULL, 3, 1020, NULL, NULL, NULL, '2023-06-08 09:02:31', NULL, '2023-06-08 09:02:31', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2121, '删除', NULL, 0, 'system:post:del', NULL, NULL, NULL, 0, b'0', b'0', b'0', b'0', NULL, b'0', NULL, 3, 1020, NULL, NULL, NULL, '2023-06-08 09:02:31', NULL, '2023-06-08 09:02:31', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2122, '查询单个值', NULL, 0, 'system:post:query', NULL, NULL, NULL, 0, b'0', b'0', b'0', b'0', NULL, b'0', NULL, 3, 1020, NULL, NULL, NULL, '2023-06-08 09:02:31', NULL, '2023-06-08 09:02:31', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2123, '新增', NULL, 0, 'system:dept:add', NULL, NULL, NULL, 0, b'0', b'0', b'0', b'0', NULL, b'0', NULL, 3, 1015, NULL, NULL, NULL, '2023-06-08 09:02:31', NULL, '2023-06-08 09:02:31', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2124, '修改', NULL, 0, 'system:dept:edit', NULL, NULL, NULL, 0, b'0', b'0', b'0', b'0', NULL, b'0', NULL, 3, 1015, NULL, NULL, NULL, '2023-06-08 09:02:31', NULL, '2023-06-08 09:02:31', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2125, '删除', NULL, 0, 'system:dept:del', NULL, NULL, NULL, 0, b'0', b'0', b'0', b'0', NULL, b'0', NULL, 3, 1015, NULL, NULL, NULL, '2023-06-08 09:02:31', NULL, '2023-06-08 09:02:31', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2126, '查询单个值', NULL, 0, 'system:dept:query', NULL, NULL, NULL, 0, b'0', b'0', b'0', b'0', NULL, b'0', NULL, 3, 1015, NULL, NULL, NULL, '2023-06-08 09:02:31', NULL, '2023-06-08 09:02:31', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2127, '新增', NULL, 0, 'system:menu:add', NULL, NULL, NULL, 0, b'0', b'0', b'0', b'0', NULL, b'0', NULL, 3, 1040, NULL, NULL, NULL, '2023-06-08 09:02:31', NULL, '2023-06-08 09:02:31', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2128, '修改', NULL, 0, 'system:menu:edit', NULL, NULL, NULL, 0, b'0', b'0', b'0', b'0', NULL, b'0', NULL, 3, 1040, NULL, NULL, NULL, '2023-06-08 09:02:31', NULL, '2023-06-08 09:02:31', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2129, '删除', NULL, 0, 'system:menu:del', NULL, NULL, NULL, 0, b'0', b'0', b'0', b'0', NULL, b'0', NULL, 3, 1040, NULL, NULL, NULL, '2023-06-08 09:02:31', NULL, '2023-06-08 09:02:31', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2130, '查询单个值', NULL, 0, 'system:menu:query', NULL, NULL, NULL, 0, b'0', b'0', b'0', b'0', NULL, b'0', NULL, 3, 1040, NULL, NULL, NULL, '2023-06-08 09:02:31', NULL, '2023-06-08 09:02:31', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2131, '新增', NULL, 0, 'system:dict:add', NULL, NULL, NULL, 0, b'0', b'0', b'0', b'0', NULL, b'0', NULL, 3, 1050, NULL, NULL, NULL, '2023-06-08 09:02:31', NULL, '2023-06-08 09:02:31', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2132, '修改', NULL, 0, 'system:dict:edit', NULL, NULL, NULL, 0, b'0', b'0', b'0', b'0', NULL, b'0', NULL, 3, 1050, NULL, NULL, NULL, '2023-06-08 09:02:31', NULL, '2023-06-08 09:02:31', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2133, '删除', NULL, 0, 'system:dict:del', NULL, NULL, NULL, 0, b'0', b'0', b'0', b'0', NULL, b'0', NULL, 3, 1050, NULL, NULL, NULL, '2023-06-08 09:02:31', NULL, '2023-06-08 09:02:31', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2134, '查询单个值', NULL, 0, 'system:dict:query', NULL, NULL, NULL, 0, b'0', b'0', b'0', b'0', NULL, b'0', NULL, 3, 1050, NULL, NULL, NULL, '2023-06-08 09:02:31', NULL, '2023-06-08 09:02:31', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2135, '新增', NULL, 0, 'system:dict-detail:add', NULL, NULL, NULL, 0, b'0', b'0', b'0', b'0', NULL, b'0', NULL, 3, 1050, NULL, NULL, NULL, '2023-06-08 09:02:31', NULL, '2023-06-08 09:02:31', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2136, '修改', NULL, 0, 'system:dict-detail:edit', NULL, NULL, NULL, 0, b'0', b'0', b'0', b'0', NULL, b'0', NULL, 3, 1050, NULL, NULL, NULL, '2023-06-08 09:02:31', NULL, '2023-06-08 09:02:31', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2137, '删除', NULL, 0, 'system:dict-detail:del', NULL, NULL, NULL, 0, b'0', b'0', b'0', b'0', NULL, b'0', NULL, 3, 1050, NULL, NULL, NULL, '2023-06-08 09:02:31', NULL, '2023-06-08 09:02:31', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2138, '查询单个值', NULL, 0, 'system:dict-detail:query', NULL, NULL, NULL, 0, b'0', b'0', b'0', b'0', NULL, b'0', NULL, 3, 1050, NULL, NULL, NULL, '2023-06-08 09:02:31', NULL, '2023-06-08 09:02:31', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2145, '系统监控', 'monitor', 30, NULL, '/monitor', NULL, NULL, 0, b'0', b'1', b'0', b'0', NULL, b'0', NULL, 1, NULL, NULL, NULL, '1', '2023-06-11 08:18:27', '1', '2023-06-11 08:18:27', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2146, '在线用户', NULL, 10, 'monitor:online:list', '/online', 'OnlineUser', 'monitor/online', 0, b'0', b'1', b'0', b'0', NULL, b'1', 'New', 2, 2145, b'1', b'1', '1', '2023-06-11 08:20:20', '1', '2023-10-20 09:19:52', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2147, '组件', 'table_layout', 48, NULL, '/components', NULL, NULL, 0, b'0', b'1', b'0', b'0', NULL, b'0', NULL, 1, NULL, NULL, NULL, '1', '2023-06-30 02:02:47', '1', '2023-06-30 02:02:47', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2148, '富文本编辑器', NULL, 0, NULL, '/editor', 'Editor', 'components/editor', 0, b'0', b'1', b'0', b'0', NULL, b'0', NULL, 2, 2147, b'1', b'1', '1', '2023-06-30 02:07:33', '1', '2023-10-20 09:19:52', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2149, '文件上传', NULL, 0, NULL, '/upload-file', NULL, 'components/demo-upload-file', 0, b'0', b'1', b'0', b'0', NULL, b'0', NULL, 2, 2147, b'1', b'1', '1', '2023-06-30 02:08:28', '1', '2023-10-20 09:19:52', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2159, '根据ID查询', NULL, 0, 'system:user:query', NULL, NULL, NULL, 0, b'0', b'0', b'0', b'0', NULL, b'0', NULL, 3, 1010, NULL, NULL, NULL, '2023-07-02 03:05:38', NULL, '2023-07-02 03:05:38', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2160, '新增', NULL, 0, 'system:user:add', NULL, NULL, NULL, 0, b'0', b'0', b'0', b'0', NULL, b'0', NULL, 3, 1010, NULL, NULL, NULL, '2023-07-02 03:05:38', NULL, '2023-07-02 03:13:14', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2162, '删除', NULL, 0, 'system:user:del', NULL, NULL, NULL, 0, b'0', b'0', b'0', b'0', NULL, b'0', NULL, 3, 1010, NULL, NULL, NULL, '2023-07-02 03:05:38', NULL, '2023-07-02 03:13:14', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2163, '导出', NULL, 0, 'system:user:export', NULL, NULL, NULL, 0, b'0', b'0', b'0', b'0', NULL, b'0', NULL, 3, 1010, NULL, NULL, NULL, '2023-07-02 03:05:38', NULL, '2023-07-02 03:13:14', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2164, '导入', NULL, 0, 'system:user:import', NULL, NULL, NULL, 0, b'0', b'0', b'0', b'0', NULL, b'0', NULL, 3, 1010, NULL, NULL, NULL, '2023-07-02 03:05:38', NULL, '2023-07-02 03:13:14', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2165, '重置密码', NULL, 0, 'system:user:resetPwd', NULL, NULL, NULL, 0, b'0', b'0', b'0', b'0', NULL, b'0', NULL, 3, 1010, NULL, NULL, NULL, '2023-07-02 03:05:38', NULL, '2023-07-02 03:13:14', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2166, '分配角色', NULL, 0, 'system:user:assignRole', NULL, NULL, NULL, 0, b'0', b'0', b'0', b'0', NULL, b'0', NULL, 3, 1010, NULL, NULL, NULL, '2023-07-02 03:05:38', NULL, '2023-07-02 03:13:14', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2167, 'Druid', NULL, 999, NULL, 'http://localhost:8000/api/druid/datasource.html', NULL, NULL, 0, b'0', b'1', b'0', b'0', NULL, b'0', NULL, 2, 2145, NULL, NULL, '1', '2023-07-12 03:46:41', NULL, '2023-07-12 03:46:41', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2174, '多级菜单', 'multi-dir', 90, NULL, '/first', NULL, NULL, 0, b'0', b'1', b'0', b'0', NULL, b'0', NULL, 1, NULL, b'1', b'1', '1', '2023-07-31 03:01:10', '1', '2023-07-31 03:01:10', NULL, 0, b'0');
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2175, '二级菜单1', NULL, 999, NULL, 'second1', NULL, NULL, 0, b'0', b'1', b'0', b'0', NULL, b'0', NULL, 1, 2174, b'1', b'1', '1', '2023-07-31 03:02:12', NULL, '2023-07-31 03:02:12', NULL, 0, b'0');
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2176, '二级菜单2', NULL, 999, NULL, 'second2', NULL, NULL, 0, b'0', b'1', b'0', b'0', NULL, b'0', NULL, 1, 2174, b'1', b'1', '1', '2023-07-31 03:02:37', NULL, '2023-07-31 03:02:37', NULL, 0, b'0');
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2177, '二级菜单3', NULL, 999, NULL, 'second3', 'Second3', 'first/second3', 0, b'0', b'1', b'0', b'0', NULL, b'0', 'New', 2, 2174, b'1', b'1', '1', '2023-07-31 03:03:39', '1', '2023-07-31 03:03:39', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2178, '三级菜单1', NULL, 999, NULL, 'third1', 'Second1Third1', 'first/second1/third1', 0, b'0', b'1', b'0', b'0', NULL, b'1', NULL, 2, 2175, b'1', b'1', '1', '2023-07-31 03:05:02', '1', '2023-07-31 03:05:02', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2179, '三级菜单2', NULL, 999, NULL, 'third2', 'Second1Third2', 'first/second1/third2', 0, b'0', b'1', b'0', b'0', NULL, b'0', NULL, 2, 2175, b'1', b'1', '1', '2023-07-31 03:05:35', NULL, '2023-07-31 03:05:35', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2180, '三级菜单1', NULL, 999, NULL, 'third1', 'Second2Third1', 'first/second2/third1', 0, b'0', b'1', b'0', b'0', NULL, b'0', NULL, 2, 2176, b'1', b'1', '1', '2023-07-31 03:05:59', NULL, '2023-07-31 03:05:59', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2181, '三级菜单2', NULL, 999, NULL, 'third2', 'Second2Third2', 'first/second2/third2', 0, b'0', b'1', b'0', b'0', NULL, b'0', '', 2, 2176, b'1', b'1', '1', '2023-07-31 03:06:23', '1', '2023-07-31 03:06:23', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2183, '二级菜单4', NULL, 999, NULL, 'second4', NULL, NULL, 0, b'0', b'1', b'0', b'0', NULL, b'0', NULL, 1, 2174, b'1', b'1', '1', '2023-08-03 12:39:57', '1', '2023-08-03 12:39:57', NULL, 0, b'0');
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2184, '三级菜单1', NULL, 999, NULL, 'third1', NULL, NULL, 0, b'0', b'1', b'0', b'0', NULL, b'0', NULL, 1, 2183, b'1', b'1', '1', '2023-08-03 12:40:33', NULL, '2023-08-03 12:40:33', NULL, 0, b'0');
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2185, '四级菜单1', NULL, 999, NULL, 'four1', 'Second4Third1Four1', 'first/second4/third1/four1', 0, b'0', b'1', b'0', b'0', NULL, b'0', NULL, 2, 2184, b'1', b'1', '1', '2023-08-03 12:41:14', '1', '2023-08-03 12:41:14', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2186, '修改', NULL, 999, 'system:user:edit', NULL, NULL, NULL, 0, b'0', b'1', b'0', b'0', NULL, b'0', NULL, 3, 1010, b'1', b'1', '1', '2023-08-04 13:53:56', NULL, '2023-08-04 13:53:56', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2187, '测试按钮', NULL, 999, NULL, NULL, NULL, NULL, 0, b'0', b'1', b'0', b'0', NULL, b'0', NULL, 3, 2185, b'1', b'1', '1', '2023-08-10 06:32:03', NULL, '2023-08-10 06:32:03', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2188, '通知公告', 'tongzhi', 999, 'system:sysNotice:list', '/sysNotice', 'SysNotice', 'system/sysNotice', 0, b'0', b'1', b'1', b'0', NULL, b'0', NULL, 2, 20, b'1', b'1', NULL, '2023-08-30 05:40:34', '1', '2023-08-30 07:13:44', NULL, 0, b'0');
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2189, '根据ID查询', NULL, 0, 'system:sysNotice:query', NULL, NULL, NULL, 0, b'0', b'0', b'0', b'0', NULL, b'0', NULL, 3, 2188, NULL, NULL, NULL, '2023-08-30 05:40:34', NULL, '2023-08-30 05:40:34', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2190, '列表', NULL, 0, 'system:sysNotice:list', NULL, NULL, NULL, 0, b'0', b'0', b'0', b'0', NULL, b'0', NULL, 3, 2188, NULL, NULL, NULL, '2023-08-30 05:40:34', NULL, '2023-08-30 05:40:34', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2191, '新增', NULL, 0, 'system:sysNotice:add', NULL, NULL, NULL, 0, b'0', b'0', b'0', b'0', NULL, b'0', NULL, 3, 2188, NULL, NULL, NULL, '2023-08-30 05:40:34', NULL, '2023-08-30 05:40:34', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2192, '修改', NULL, 0, 'system:sysNotice:edit', NULL, NULL, NULL, 0, b'0', b'0', b'0', b'0', NULL, b'0', NULL, 3, 2188, NULL, NULL, NULL, '2023-08-30 05:40:34', NULL, '2023-08-30 05:40:34', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2193, '删除', NULL, 0, 'system:sysNotice:del', NULL, NULL, NULL, 0, b'0', b'0', b'0', b'0', NULL, b'0', NULL, 3, 2188, NULL, NULL, NULL, '2023-08-30 05:40:34', NULL, '2023-08-30 05:40:34', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2194, '导出', NULL, 0, 'system:sysNotice:export', NULL, NULL, NULL, 0, b'0', b'0', b'0', b'0', NULL, b'0', NULL, 3, 2188, NULL, NULL, NULL, '2023-08-30 05:40:34', NULL, '2023-08-30 05:40:34', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2195, '导入', NULL, 0, 'system:sysNotice:import', NULL, NULL, NULL, 0, b'0', b'0', b'0', b'0', NULL, b'0', NULL, 3, 2188, NULL, NULL, NULL, '2023-08-30 05:40:34', NULL, '2023-08-30 05:40:34', NULL, 0, NULL);
INSERT INTO `sys_menu` (`id`, `menu_name`, `menu_icon`, `sort_num`, `permission`, `path`, `component_name`, `component`, `status`, `affix`, `visible`, `cache`, `embed`, `embed_url`, `dot`, `badge`, `menu_type`, `parent_id`, `show_header`, `show_footer`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`, `always_show`) VALUES (2196, '一级菜单', 'shortcut', 100, NULL, '/one', 'First', 'first', 0, b'0', b'1', b'0', b'0', NULL, b'0', NULL, 2, NULL, b'1', b'1', '1', '2023-09-05 08:46:45', '1', '2023-09-05 08:46:45', NULL, 0, b'0');
COMMIT;

-- ----------------------------
-- Records of sys_notice
-- ----------------------------
BEGIN;
INSERT INTO `sys_notice` (`id`, `title`, `type`, `description`, `content`, `status`, `publisher`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`) VALUES ('1696788131262599170', '新版发布通知', 0, '🔥EuBackend v1.0.0版本采用Vue2+ElementUI全新发布！', '<h1>新版发布通知</h1><h3>🔥EuBackend v1.0.0版本采用Vue2+ElementUI全新发布！</h3><ul><li>测试内容测试内容测试内容测试内容</li><li>测试内容测试内容测试内容测试内容</li><li>测试内容测试内容测试内容测试内容</li></ul><pre><code >This is My Editor</code></pre><p><br></p>', 0, 'Eu.z', '1', '2023-08-30 07:33:09', '1', '2023-08-30 08:08:25', NULL, 0);
INSERT INTO `sys_notice` (`id`, `title`, `type`, `description`, `content`, `status`, `publisher`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`) VALUES ('1696797959468982273', '「通知公告」功能上线啦', 1, '🔥EuBackend v1.1.0 新增「通知公告」功能，欢迎使用！', '<h1>「通知公告」功能上线啦</h1><h3>🔥EuBackend v1.1.0 新增「通知公告」功能，欢迎使用！</h3><ol><li>系统设置/通知公告</li><li>右上角通知图标</li></ol>', 0, '系统管理员', '1', '2023-08-30 08:12:13', NULL, '2023-08-30 08:12:13', NULL, 0);
COMMIT;

-- ----------------------------
-- Records of sys_role
-- ----------------------------
BEGIN;
INSERT INTO `sys_role` (`id`, `role_key`, `role_name`, `description`, `status`, `data_scope`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`) VALUES (1, 'admin', '系统管理员', '拥有网站的全部权限', 0, NULL, NULL, '2023-06-05 07:53:20', NULL, '2023-06-05 07:53:20', NULL, 0);
COMMIT;

-- ----------------------------
-- Records of sys_user
-- ----------------------------
BEGIN;
INSERT INTO `sys_user` (`id`, `username`, `nickname`, `avatar`, `mobile`, `email`, `password`, `sex`, `admin`, `dept_id`, `status`, `login_ip`, `login_time`, `last_active_time`, `password_reset_time`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `del_flag`) VALUES ('1', 'admin', '系统管理员', 'http://localhost:8000/api/upload/download?path=/1705115342541778944.png', '18500000000', 'admin@eu.com', '$2a$05$QMz7BBsK6eUl4VpUt9fFZeoonk.qUEFVR2vLwKOs6p1kP4aVQVPCm', 1, 1, NULL, 0, '127.0.0.1', '2023-10-20 15:38:30', '2023-10-20 17:28:33', '2023-09-20 22:32:04', NULL, '2023-06-05 05:59:02', '1', '2023-10-20 09:28:33', NULL, 0);
COMMIT;

-- ----------------------------
-- Records of sys_user_role
-- ----------------------------
BEGIN;
INSERT INTO `sys_user_role` (`role_id`, `user_id`) VALUES (1, '1');
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
